### ISSUE TITLE
relation "users" does not exist

### ISSUE THREAD

**Issue by naderchehab** [HashNuke/mogo-chat#6]
Hi, great project, installation is a breeze considering all the work it's doing in the background! However I have an issue. The installation seemed to go well however when I try to login I get the following error:

```
POST http://<myurl>.herokuapp.com/api/sessions 500 (Internal Server Error) 
```

Taking a peak at the HTTP response I see this:

```
  <html>
    <h2>(Postgrex.Error) ERROR (42P01): relation "users" does not exist</h2>
    <h4>Stacktrace</h4>
    <pre>    lib/ecto/adapters/postgres/worker.ex:21: Ecto.Adapters.Postgres.Worker.query!/4
    lib/ecto/adapters/postgres.ex:242: Ecto.Adapters.Postgres.use_worker/3
    lib/ecto/adapters/postgres.ex:48: Ecto.Adapters.Postgres.all/3
    (mogo_chat) lib/mogo_chat/controllers/sessions_api.ex:37: MogoChat.Controllers.SessionsApi.login/3
    (mogo_chat) lib/mogo_chat/router.ex:1: anonymous fn/1 in MogoChat.Router.call/2
    (mogo_chat) lib/mogo_chat/plugs/session.ex:36: Plugs.Session.wrap/3
    (mogo_chat) lib/mogo_chat/auth_error_handler.ex:12: MogoChat.AuthErrorHandler.wrap/3
    (phoenix) lib/phoenix/plugs/error_handler.ex:8: Phoenix.Plugs.ErrorHandler.wrap/3
</pre>
  </html>
```

Any idea why the "users" relation was not created initially?

**Comment by HashNuke** [comment]
@naderchehab Hey Nader, it's most likely that the git push failed and hence the commands after that. The git push might have failed due to dependencies not being fetched properly (Github not being available at the same time of deployment will cause a problem).

Can you try deploying again?

Closing this issue for now. But if you still encounter this problem, please do report back (along with the console output of the deployment) and I will look into it.
